### PR TITLE
meta: charter the LTS Working Group

### PR DESCRIPTION
**Pull request by jasnell**
It's about time that we officially charter the LTS Working Group.

/cc @nodejs/ctc @nodejs/lts

### CODE REVIEW

**Comment by nebrius** [comment]
According to the [working group documentation](https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md#starting-a-wg), the first step is for the WG to present a charter to the CTC to be ratified.

Looking at the LTS README, a lot of the required information is already there (good job LTS!), so hopefully it won't be hard to convert it to an official charter document. The big thing I see that is missing is some official wording on how to become a member. It doesn't have to be in depth, but it _is_ needed, and it's a good thing to have anyways WG or not.

**Comment by jasnell** [comment]
Yep. I plan to bring this up on the next LTS WG (that reminds me to attach the label :-) ...) to fill out the details. The draft in this PR was taken from an old open discussion and may not be up to date.

**Comment by Trott** [comment]
@nebrius wrote:

> According to the working group documentation, the first step is for the WG to present a charter to the CTC to be ratified.

Wouldn't it be the TSC and not the CTC? The first line of the document linked to says:

> Node.js Working Groups are autonomous projects created by the Technical Steering Committee (TSC).

Help us @williamkapke, you're our only hope.

**Comment by sam-github** [comment]
Both the TSC and the CTC can charter working groups. I assume this would be a CTC WG, the distinction is about as clear as the TSC vs CTC distinction.

**Comment by Trott** [comment]
> Both the TSC and the CTC can charter working groups. I assume this would be a CTC WG, the distinction is about as clear as the TSC vs CTC distinction.

I guess that doc needs to be updated. It refers to TSC a lot but only mentions CTC once and in a vague way. And it mentions `TC` a lot but I don't think it ever defines what it means by that.

**Comment by mhdawson** [comment]
In the last LTS meeting I took the action to put together our recommendation for chartering which involves both the existing LTS and Release teams.  We still need input from the release team members once we have an initial suggestion.

**Comment by mhdawson** [comment]
@Trott I suspect the CTC is not mentioned because when the doc was initially written their was only the TSC.  When the groups were split my understanding was that the intent was that the existing WGs would be delegated their responsibility from the CTC.

**Comment by Trott** [comment]
One thing that should happen before chartering LTS as a working group is a cleanup of the LTS team (@nodejs/lts). I suspect there are people on that team that are not active in the proto-WG.

**Comment by mhdawson** [comment]
We should probably let https://github.com/nodejs/LTS/pull/223 settle and then update this PR.

**Comment by jasnell** [comment]
@mhdawson ... feel free to push any additional commits necessary to this PR to get it ready to land.

**Comment by mhdawson** [comment]
Replaced by https://github.com/nodejs/CTC/pull/167

**Pull request closed without merging**
