### PR TITLE
add meeting schedule

### PR DESCRIPTION
**Pull request by Trott**
Not sure that the README is the best place for the meeting schedule table, but unless/until we come up with something better, let's put it there for now, eh?  /cc @nodejs/ctc

### CODE REVIEW

**Comment by mhdawson** [comment]
LGTM

**Review by cjihrig — APPROVED** [review]

**Review by jasnell — APPROVED** [review]
LGTM

**Comment by williamkapke** [comment]
This is a bit of a tangent but.. should the Meeting Notices/Agendas start being posted in this repo instead? I really feel that the Node repo is just too high volume to include these. Maybe have a transition period where an issue is also posted to node linking to the CTC issue. WDYT?

**Comment by jasnell** [comment]
I would definitely prefer the meeting notices to be posted here.

**Comment by MylesBorins** [comment]
+1 on meeting notices here

**Pull request merged**
